import mapconfigshare from '@/config/mapconfigshare.js';
const mapconfig = {
  jsApiUrl: mapconfigshare.jsApiUrl,
  cssUrl: mapconfigshare.cssUrl,
  proxyConifg: mapconfigshare.proxyConifg,
  extent: mapconfigshare.extent,
  Gridcamera: mapconfigshare.Gridcamera,
  gisTokenServer: mapconfigshare.gisTokenServer,
  PgHightlightsymbol: mapconfigshare.PgHightlightsymbol,
  PointHightlightsymbol: mapconfigshare.PointHightlightsymbol,
  PointSelectedHight: mapconfigshare.PointSelectedHight,
  PolylineHightsymbol: mapconfigshare.PolylineHightsymbol,
  GISService: {
    geometryService: mapconfigshare.GISService.geometryService,
    baseMapServices: mapconfigshare.GISService.baseMapServices,
    operationLayers: mapconfigshare.GISService.operationLayers,

    bussinesslayer: {
      serverurl: "http://10.81.71.50/arcgis/rest/services",
      istoken: false,
      tokenType: "arcgis",
      layers: [{
          url: "http://10.101.42.199:8080/arcgis/rest/services/xh/XHWebM0822/MapServer",
          id: "XH_DT_New",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "MapImageLayer",
          tag: "徐汇网格化数据",
          title: "徐汇网格化数据",
          type: "image",
          listMode: 'hide',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        }, {
          url: "http://10.101.42.199:8080/arcgis/rest/services/xh/XHWebM0822/MapServer",
          id: "XH_DT_New",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "SHCDMapImageLayer",
          tileurl: "http://31.0.37.225/arcgis_js_api/library/4.12/esri/layers/json/tileJson.json",
          tag: "徐汇网格化数据",
          title: "徐汇网格化数据",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        }]
    },

    xuhuilayers: {
      serverurl: "http://hostserver.xhbd.local/arcgis/rest/services",
      istoken: false,
      tokenType: "arcgis",
      layers: [{
          url: "http://hostserver.xhbd.local/arcgis/rest/services/Hosted/XH_QX_LH/SceneServer",
          id: "QXCH_LH",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "SceneLayer",
          tag: "全息测绘",
          title: "全息测绘",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        },
        {
          url: "http://hostserver.xhbd.local/arcgis/rest/services/XU_WG/MapServer",
          id: "XH_WG",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "MapImageLayer",
          tag: "网格",
          title: "网格",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        }, {
          url: "http://hostserver.xhbd.local/arcgis/rest/services/XHGQ/MapServer",
          id: "XH_GQ",
          istoken: false,
          visible: true,
          opacity: 1.0,
          maptype: "TileLayer",
          tag: "徐汇区分区描边",
          title:"徐汇区分区描边",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        },{
            id: "XH_Graphiclayer",
            istoken: false,
            visible: true,
            opacity: 1.0,
            maptype: "GraphicsLayer",
            tag: "辅助显示图层",
            title: "辅助显示图层",
            type: "image",
            listMode: 'hide',
            imageUrl: require("../assets/basemap/mapType_img.jpg"),
        },{
          url: "http://hostserver.xhbd.local/arcgis/rest/services/XU_JD/MapServer",
          id: "XH_JD",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "FeatureLayer",
          tag: "徐汇区街道",
          title: "徐汇区街道",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        }, {
          url: "http://hostserver.xhbd.local/arcgis/rest/services/XU_JD/MapServer",
          id: "XH_JWH",
          istoken: false,
          visible: false,
          opacity: 1.0,
          maptype: "FeatureLayer",
          tag: "徐汇居委会",
          title: "徐汇居委会",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        },
         {
          url: "http://hostserver.xhbd.local/arcgis/rest/services/Hosted/cameraPoint/FeatureServer",
          id: "XH_VideoCamera",
          istoken: false,
          visible: false,
          opacity: 1.0,
          screenSizePerspectiveEnabled: true,
          maptype: "FeatureLayer",
          tag: "徐汇区摄像头",
          title: "徐汇区摄像头",
          type: "image",
          listMode: 'show',
          imageUrl: require("../assets/basemap/mapType_img.jpg"),
        }
      ]
    }
  },
};
export default mapconfig;
